name: 'action-init'
description: 'a GitHub action to initialize repositories created from templates in Kaskadi'
runs:
  using: 'node12'
  pre: 'dist/setup.js'
  main: 'dist/main.js'
  post: 'dist/cleanup.js'
