name: 'action-init'
description: 'a GitHub action to initialize repositories created from templates in Kaskadi'
inputs:
  repoType:
    description: 'Type of repository to initialize'
    required: true
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
