const core = require('@actions/core')
const { spawnSync } = require('child_process')
const { installCLI, removeCLI } = require('./helpers/kaskadi-cli-manager')
const initRepo = require('./helpers/init-repo.js')
const cleanup = require('./helpers/cleanup.js')
const pushChanges = require('./helpers/push-changes.js')
const repoType = core.getInput('repoType')
installCLI(spawnSync)
initRepo(spawnSync, repoType)
removeCLI(spawnSync)
cleanup(spawnSync)
pushChanges(spawnSync)
