const { spawnSync } = require('child_process')
console.log('INFO: removing kaskadi-cli from repository...')
console.log('************ NPM ouput ************')
spawnSync('npm', ['rm', 'kaskadi-cli'], { stdio: 'inherit' })
console.log('************ End of NPM ouput ************')
console.log('SUCCESS: kaskadi-cli removed!')
console.log('INFO: removing init workflow from repository...')
spawnSync('git', ['rm', '.github/workflows/init.yml'], { stdio: 'inherit' })
console.log('SUCCESS: successfully removed workflow!')
console.log('INFO: commiting and pushing changes...')
const gpgSign = spawnSync('git', ['config', 'commit.gpgSign']).stdout
const commitParams = gpgSign.length > 0 ? ['commit', '-S', '-am', 'Initialized repository with correct naming'] : ['commit', '-am', 'Initialized repository with correct naming']
spawnSync('git', commitParams, { stdio: 'inherit' })
spawnSync('git', ['push'], { stdio: 'inherit' })
console.log('SUCCESS: commited and pushed changes!')
