name: generate-docs
on:
  push:
    branches:
      - 'master'
    paths:
      - 'action.yml'
      - 'docs/**'
      - 'package.json'
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v2
      with:
        git_user_signingkey: true
        git_commit_gpgsign: true
      env:
        GPG_PRIVATE_KEY: ${{ secrets.KASKADI_BOT_GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.KASKADI_BOT_GPG_PRIVATE_PASSPHRASE }}
    - name: Generate documentation
      uses: kaskadi/action-generate-docs@master
      with:
        type: action
        template: docs/template.md